version: '2.30.0'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: armando1gaspar 
      MYSQL_DATABASE: san_agustin         
      MYSQL_USER: gaspar                  
      MYSQL_PASSWORD: armando1gaspar      
    ports:
      - "3307:3306"                       
    volumes:
      - mysql_data:/var/lib/mysql         

volumes:
  mysql_data:
