"""2 migraciones desde cero

Revision ID: a7bcd1b64c75
Revises: 
Create Date: 2024-09-11 11:28:18.760461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7bcd1b64c75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paralelo', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('name_paralelo', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('name_paralelo')
        batch_op.drop_column('paralelo')

    # ### end Alembic commands ###
